# Generated by Django 5.1.3 on 2024-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_date',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
