# Generated by Django 5.1.3 on 2024-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_blogs_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
