# Generated by Django 5.1.3 on 2024-11-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_app_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='role',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
    ]
