# Generated by Django 5.1.3 on 2024-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_app_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='role',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
